---
title: Tamy Tsujimoto's Resume"
author: Tamy Tsujimoto
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/custom_resume.css', 'css/styles.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---


```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(tidyverse)
library(glue)

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- FALSE

# Holds all the links that were inserted for placement at the end
links <- c()

source('parsing_functions.R')


# First let's get the data, filtering to only the items tagged as
# Resume items
position_data <- read_csv('positions.csv') %>% 
  filter(in_resume)
  # mutate(
  #   # Build some custom sections by collapsing others
  #   section = case_when(
  #     section %in% c('research_positions', 'industry_positions') ~ 'positions', 
  #     section %in% c('data_science_writings', 'by_me_press') ~ 'writings',
  #     TRUE ~ section
  #   )
  # ) 

```


Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------


- <i class="fa fa-envelope"></i> tharumy@live.unc.edu
- <i class="fa fa-github"></i> [tamytsujimoto](https://github.com/tamytsujimoto)
- <i class="fa fa-linkedin"></i> [tamy-tsujimoto](https://www.linkedin.com/in/tamy-tsujimoto)
<!-- - <i class="fa fa-link"></i> [nickstrayer.me](http://nickstrayer.me/) -->
- <i class="fa fa-phone"></i> +1 (919) 593-9074


Skills {#skills}
--------------------------------------------------------------------------------

```{r}
skills <- tribble(
  ~skill,               ~level,
  "R",                  5,
  "SPSS",               5,
  "SAS",                4,
  "Stata",              4,
  "Python",             2.5
)

build_skill_bars(skills)
```

Languages {#language}
--------------------------------------------------------------------------------

Portuguese: Native

English: Fluent

<!-- Open Source Contributions {#open-source} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- All projects available at `github.com/nstrayer/<name>` -->


<!-- - `shinysense`: R package to use sensor data in Shiny apps -->
<!-- - `tuftesque`: Hugo theme (behind LiveFreeOrDichotomize.com) -->
<!-- - `slid3r`: D3 add-on for fully svg slider inputs -->


<!-- More info {#more-info} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- See full CV at nickstrayer.me/cv for more complete list of positions and publications. -->


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with [**pagedown**](https://github.com/rstudio/pagedown). 
<!-- Source code: [github.com/nstrayer/cv](https://github.com/nstrayer/cv). -->

Last updated on `r Sys.Date()`.


Main
================================================================================

Tamy Harumy Moraes Tsujimoto {#title}
--------------------------------------------------------------------------------

```{r}
intro_text <- 
"
PhD candidate in Biostatistics currently searching for 2020 summer internship
"


cat(sanitize_links(intro_text))
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'education')
```

Industry Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'industry')
```

Professional Development {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'professional_dvlp')
```
